GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs
content-type: application/json

{
  "title": "Hi",
  "author": "Joe",
  "url": "http://something.com",
  "likes": 10
}

###
DELETE http://localhost:3001/api/blogs/654af74813524cfe85adcc03