GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJvYiIsImlkIjoiNjU0YmI2MzE5NjY4ZTE4MjBmMTU2NTU5IiwiaWF0IjoxNjk5NDYxMzIzfQ.Yx2OEoT-Jg27P98nBvXQcMKTxx1IWkpAWmIkBMMlZtE

{
  "title": "Hi",
  "author": "Joe",
  "url": "http://something.com",
  "likes": 10,
  "userId": "654bb201ea3a002a19cc6812"
}

###
DELETE http://localhost:3001/api/blogs/654af74813524cfe85adcc03

###
PUT http://localhost:3001/api/blogs/654af9698a3c612dbcb31b72
content-type: application/json

{
    "title": "asdf",
    "author": "asdf",
    "url": "http://blog.cleancoder.com/uncle-bob/2017/05/05/TestDefinitions.htmll",
    "likes": 9000
}