GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs
content-type: application/json

{
  "title": "Hi",
  "author": "Joe",
  "url": "http://something.com",
  "likes": 10
}

###
DELETE http://localhost:3001/api/blogs/654af74813524cfe85adcc03

###
PUT http://localhost:3001/api/blogs/654af9698a3c612dbcb31b72
content-type: application/json

{
    "title": "asdf",
    "author": "asdf",
    "url": "http://blog.cleancoder.com/uncle-bob/2017/05/05/TestDefinitions.htmll",
    "likes": 9000
}