GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJvYiIsImlkIjoiNjU0YmNjMmU4MzdjYjYwN2E4MmVmNzBhIiwiaWF0IjoxNjk5NDY3MDE5LCJleHAiOjE2OTk0NzA2MTl9.lfuAP3NG2n93qmBq5uDsaYjTS51RTCTK0ESbJ_PEqts

{
  "title": "Hi",
  "author": "Joe",
  "url": "http://something.com",
  "likes": 10
}

###
DELETE http://localhost:3001/api/blogs/654af74813524cfe85adcc03

###
PUT http://localhost:3001/api/blogs/654af9698a3c612dbcb31b72
content-type: application/json

{
    "title": "asdf",
    "author": "asdf",
    "url": "http://blog.cleancoder.com/uncle-bob/2017/05/05/TestDefinitions.htmll",
    "likes": 9000
}