GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/65493ba6ef6656dfb02a5256

###
GET http://localhost:3001/info

###
DELETE http://localhost:3001/api/persons/1

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Sam",
    "number": "123-45678"
}
 
###
PUT http://localhost:3001/api/persons/65493ba6ef6656dfb02a5256
content-type: application/json

{
    "name": "Sam",
    "number": "111-111-1111"
}